// Tax-law corpus schema and migration tests (Phase 5A). Read-only introspection
// of the real database, plus constraint checks that run in transactions which
// are always rolled back.
//
// What must hold: the three corpus tables exist and belong to nobody (no user
// column, no link to any user table); chunks belong to a source and go with it;
// (source, chunk index) is unique; PostgreSQL generates the full-text vector
// and a GIN index serves it; integrity checks reject nonsense; and the
// migration touches only the new tax_* objects, leaving every existing table's
// structure exactly as it was.
import "../db/load-env";
import fs from "node:fs";
import path from "node:path";
import { test } from "node:test";
import assert from "node:assert/strict";
import { sql } from "drizzle-orm";
import { db } from "../db/client";
import { isForeignKeyViolation, isUniqueViolation, pgErrorCode } from "../db/pg-errors";
import { taxSourceChunks, taxSources } from "../db/schema";
import { sha256Text } from "../lib/rag/corpus";
import { inRolledBackTransaction, insertFixtureSource } from "./helpers-rag";

const FRONTEND = path.resolve(__dirname, "..");
const TAX_TABLES = ["tax_sources", "tax_source_chunks", "tax_corpus_releases"];

async function rows<T extends Record<string, unknown>>(query: ReturnType<typeof sql>): Promise<T[]> {
  return (await db.execute(query)).rows as unknown as T[];
}

test("the three corpus tables exist with the columns the design calls for", async () => {
  const columns = async (table: string) =>
    (await rows<{ column_name: string }>(sql`select column_name from information_schema.columns where table_schema = 'public' and table_name = ${table} order by column_name`)).map((r) => r.column_name);

  assert.deepEqual(await columns("tax_sources"), [
    "assessment_year", "authority_tier", "content_sha256", "effective_from", "effective_to", "governing_act",
    "id", "publisher", "retrieved_at", "source_date", "source_key", "status", "title", "url",
  ]);
  assert.deepEqual(await columns("tax_source_chunks"), [
    "char_end", "char_start", "chunk_index", "heading_path", "id", "regime", "search_vector", "section_ref",
    "source_id", "text", "text_sha256", "topics", "verification_status",
  ]);
  assert.deepEqual(await columns("tax_corpus_releases"), ["created_at", "id", "manifest_sha256", "version"]);
});

test("the corpus belongs to nobody: no user column and no link to any other table but its own source", async () => {
  const userish = await rows<{ table_name: string; column_name: string }>(
    sql`select table_name, column_name from information_schema.columns where table_schema = 'public' and table_name in ('tax_sources','tax_source_chunks','tax_corpus_releases') and (column_name ilike '%user%' or column_name ilike '%owner%')`,
  );
  assert.deepEqual(userish, []);

  const foreignKeys = await rows<{ from_table: string; to_table: string; on_delete: string }>(sql`
    select cl.relname as from_table, ref.relname as to_table, c.confdeltype as on_delete
    from pg_constraint c
    join pg_class cl on cl.oid = c.conrelid
    join pg_class ref on ref.oid = c.confrelid
    where c.contype = 'f' and (cl.relname like 'tax\\_source%' or cl.relname = 'tax_corpus_releases' or ref.relname like 'tax\\_source%')
  `);
  assert.deepEqual(foreignKeys.map((f) => `${f.from_table}->${f.to_table}:${f.on_delete}`), ["tax_source_chunks->tax_sources:c"], "the only link is chunk -> its source, cascading");
});

test("(source, chunk index) is unique, and section, year and full-text lookups are indexed", async () => {
  const indexes = await rows<{ indexname: string; indexdef: string }>(
    sql`select indexname, indexdef from pg_indexes where schemaname = 'public' and tablename in ('tax_sources','tax_source_chunks','tax_corpus_releases')`,
  );
  const def = (name: string) => indexes.find((i) => i.indexname === name)?.indexdef ?? "";

  assert.match(def("tax_source_chunks_source_id_chunk_index_unique"), /CREATE UNIQUE INDEX .* \(source_id, chunk_index\)/);
  assert.match(def("tax_sources_source_key_unique"), /CREATE UNIQUE INDEX .* \(source_key\)/);
  assert.match(def("tax_corpus_releases_version_unique"), /UNIQUE .* \(version\)/);
  assert.match(def("tax_corpus_releases_manifest_sha256_unique"), /UNIQUE .* \(manifest_sha256\)/);
  assert.match(def("tax_source_chunks_section_ref_idx"), /\(section_ref\)/);
  assert.match(def("tax_sources_assessment_year_status_idx"), /\(assessment_year, status\)/);
  assert.match(def("tax_source_chunks_search_vector_idx"), /USING gin \(search_vector\)/);
});

test("the full-text vector is generated by PostgreSQL, so it can never disagree with the text", async () => {
  const [column] = await rows<{ data_type: string; generated: string }>(
    sql`select format_type(a.atttypid, a.atttypmod) as data_type, a.attgenerated as generated
        from pg_attribute a join pg_class c on c.oid = a.attrelid
        where c.relname = 'tax_source_chunks' and a.attname = 'search_vector'`,
  );
  assert.equal(column.data_type, "tsvector");
  assert.equal(column.generated, "s", "a STORED generated column");

  await inRolledBackTransaction(async (tx) => {
    await insertFixtureSource(tx, { sourceKey: "fixture-tsv", chunks: [{ text: "Rebate of up to one hundred percent", sectionRef: "99Z" }] });
    const [row] = (await tx.execute<{ sv: string }>(sql`select search_vector::text as sv from tax_source_chunks c join tax_sources s on s.id = c.source_id where s.source_key = 'fixture-tsv'`)).rows;
    assert.match(row.sv, /'99z':1A/, "the section reference has the highest weight");
    assert.match(row.sv, /'rebat':\d+C/, "the text is stemmed and weighted lower");
  });
});

test("the enums hold exactly the vocabulary the corpus uses", async () => {
  const values = async (type: string) =>
    (await rows<{ enumlabel: string }>(sql`select e.enumlabel from pg_enum e join pg_type t on t.oid = e.enumtypid where t.typname = ${type} order by e.enumsortorder`)).map((r) => r.enumlabel);
  assert.deepEqual(await values("tax_authority_tier"), ["statute", "notification_circular", "official_guidance"]);
  assert.deepEqual(await values("tax_source_status"), ["active", "superseded", "withdrawn"]);
  assert.deepEqual(await values("tax_chunk_regime"), ["old", "new", "both"]);
  assert.deepEqual(await values("tax_verification_status"), ["primary_verified", "engine_not_modelled"]);
});

test("the database refuses a duplicate chunk position, a bad range, bad dates and an orphan chunk", async () => {
  await inRolledBackTransaction(async (tx) => {
    const sourceId = await insertFixtureSource(tx, { sourceKey: "fixture-constraints", chunks: [{ text: "zorblax" }] });
    const chunk = { sourceId, headingPath: ["x"], text: "t", textSha256: sha256Text("t"), regime: "both" as const, topics: [], verificationStatus: "primary_verified" as const };

    // Each attempt runs in a savepoint, so one failure does not abort the surrounding transaction.
    await assert.rejects(() => tx.transaction((inner) => inner.insert(taxSourceChunks).values({ ...chunk, chunkIndex: 0, charStart: 0, charEnd: 1 })), (e: unknown) => isUniqueViolation(e), "same (source, chunk index)");
    await assert.rejects(() => tx.transaction((inner) => inner.insert(taxSourceChunks).values({ ...chunk, chunkIndex: 5, charStart: 4, charEnd: 4 })), (e: unknown) => pgErrorCode(e) === "23514", "an empty range");
    await assert.rejects(() => tx.transaction((inner) => inner.insert(taxSourceChunks).values({ ...chunk, chunkIndex: 5, charStart: -1, charEnd: 2 })), (e: unknown) => pgErrorCode(e) === "23514", "a negative offset");
    await assert.rejects(() => tx.transaction((inner) => inner.insert(taxSourceChunks).values({ ...chunk, chunkIndex: -1, charStart: 0, charEnd: 1 })), (e: unknown) => pgErrorCode(e) === "23514", "a negative chunk index");
    await assert.rejects(
      () => tx.transaction((inner) => inner.insert(taxSourceChunks).values({ ...chunk, sourceId: "00000000-0000-4000-8000-000000000000", chunkIndex: 0, charStart: 0, charEnd: 1 })),
      (e: unknown) => isForeignKeyViolation(e),
      "a chunk with no source",
    );
    await assert.rejects(
      () =>
        tx.transaction((inner) =>
          inner.insert(taxSources).values({
            sourceKey: "fixture-bad-dates", title: "t", publisher: "p", url: "https://x.gov.in/", authorityTier: "statute", governingAct: "Income-tax Act, 1961",
            assessmentYear: "2026-27", effectiveFrom: "2026-05-01", effectiveTo: "2026-01-01", retrievedAt: new Date(), contentSha256: "x",
          }),
        ),
      (e: unknown) => pgErrorCode(e) === "23514",
      "effective dates out of order",
    );
  });
});

test("deleting a source deletes its chunks", async () => {
  await inRolledBackTransaction(async (tx) => {
    const sourceId = await insertFixtureSource(tx, { sourceKey: "fixture-cascade", chunks: [{ text: "a" }, { text: "b" }] });
    const count = async () => (await tx.execute<{ n: number }>(sql`select count(*)::int as n from tax_source_chunks where source_id = ${sourceId}`)).rows[0].n;
    assert.equal(await count(), 2);
    await tx.execute(sql`delete from tax_sources where id = ${sourceId}`);
    assert.equal(await count(), 0);
  });
});

// --- the migration itself ------------------------------------------------------------

const MIGRATION = fs.readFileSync(path.join(FRONTEND, "drizzle", "0003_tax_corpus.sql"), "utf8");

test("the migration is journaled, and every statement in it concerns only tax_* objects", () => {
  const journal = JSON.parse(fs.readFileSync(path.join(FRONTEND, "drizzle", "meta", "_journal.json"), "utf8")) as { entries: Array<{ idx: number; tag: string }> };
  assert.ok(journal.entries.some((e) => e.idx === 3 && e.tag === "0003_tax_corpus"));

  const statements = MIGRATION.split("--> statement-breakpoint").map((s) => s.trim()).filter(Boolean);
  assert.ok(statements.length >= 10);
  for (const statement of statements) assert.match(statement, /tax_/, `not a corpus statement: ${statement.slice(0, 80)}`);
  // Nothing alters an existing table: the only ALTER is adding the chunk -> source foreign key.
  const alters = statements.filter((s) => /^ALTER TABLE/.test(s));
  assert.equal(alters.length, 1);
  assert.match(alters[0], /^ALTER TABLE "tax_source_chunks" ADD CONSTRAINT .* REFERENCES "public"\."tax_sources"/);
  assert.doesNotMatch(MIGRATION, /user/i, "the migration mentions no user table or column");
  // By statement verb, so the foreign key's "ON DELETE cascade ON UPDATE no action" clause is not mistaken for a write.
  for (const statement of statements) assert.doesNotMatch(statement, /^(DROP|TRUNCATE|DELETE|UPDATE|INSERT|GRANT|REVOKE)/, "the migration neither destroys nor writes data");
  assert.match(MIGRATION, /GENERATED ALWAYS AS .* STORED/);
  assert.match(MIGRATION, /USING gin \("search_vector"\)/);
});

test("every existing table has exactly the structure it had before this migration", () => {
  const before = JSON.parse(fs.readFileSync(path.join(FRONTEND, "drizzle", "meta", "0002_snapshot.json"), "utf8")).tables as Record<string, unknown>;
  const after = JSON.parse(fs.readFileSync(path.join(FRONTEND, "drizzle", "meta", "0003_snapshot.json"), "utf8")).tables as Record<string, unknown>;

  for (const name of Object.keys(before)) assert.deepEqual(after[name], before[name], `${name} changed`);
  const added = Object.keys(after).filter((name) => !(name in before)).sort();
  assert.deepEqual(added, TAX_TABLES.map((t) => `public.${t}`).sort());
});
